#version: "3.9"

services:
  app:
    build:
      context: .
      args:
        - DEV=true
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
      - app-media:/app/media
    command: >
      sh -c "python manage.py wait_for_db &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    environment:
      - DB_HOST=db
      - DB_NAME=tdd_backend_django_dev_db
      - DB_USER=devuser
      - DB_PASS=Admin
    env_file:
      - path: .env
        required: false
    depends_on:
      - db
  
  db:
    image: mysql:8.0.43-debian
    volumes:
      - dev-db-data:/var/lib/mysql
      - ./db/init:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_DATABASE=tdd_backend_django_dev_db
      - MYSQL_USER=devuser
      - MYSQL_PASSWORD=Admin
      - MYSQL_ROOT_PASSWORD=rootpass

volumes:
  dev-db-data:
  app-media: